table Orders
    description: Orders used for booked-sales analysis
    annotation DataAgent.Source = DEMO.ANALYTICS.ORDERS

    column OrderId
        dataType: int64
        sourceColumn: ORDER_ID
        isKey: true

    column OrderDate
        dataType: dateTime
        sourceColumn: ORDER_DATE

    column CustomerId
        dataType: int64
        sourceColumn: CUSTOMER_ID

    column SalesAmount
        dataType: decimal
        sourceColumn: SALES_AMOUNT
        description: Booked sales amount
        displayFolder: Sales

    column Margin = [SalesAmount] * 0.1
        dataType: decimal
        description: Illustrative calculated margin
        displayFolder: Sales

    measure 'Total Sales' = SUM(Orders[SalesAmount])
        formatString: "$"#,0.00
